apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-logging
  namespace: kube-system
  labels:
    k8s-app: elasticsearch-logging
    version: v6.1.3
    kubernetes.io/cluster-service: "true"
    stack: logging
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20G
---

