# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   namespace: kube-system
#   name: standard
#   annotations:
#     storageclass.beta.kubernetes.io/is-default-class: "true"
#   labels:
#     addonmanager.kubernetes.io/mode: Reconcile
# provisioner: kubernetes.io/host-path

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  # name: slow
  name: standard
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  zone: eu-west-1a
  # type: io1
  # zones: eu-west-1a, eu-west-1b
  # iopsPerGB: "10"
reclaimPolicy: Retain
mountOptions:
  - debug
